### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by steveyout** [nicelife90/BladeBTC#11]
Do i have to set webhook

**Comment by nicelife90** [comment]
Hi,

if you follow the install instruction with the install script the webhook was already set for you.

**Comment by steveyout** [comment]
what about the server domain is it the one i pointed my ip address at

**Comment by nicelife90** [comment]
Yes

**Comment by steveyout** [comment]
One more question do i have to open all ports or just one

**Comment by steveyout** [comment]
Plus i get this error when connecting to domain,, connection timed out

**Comment by nicelife90** [comment]
You need to open all port from the documentation that i wrote on the main page.
