### ISSUE TITLE
/var/www/bot//vendor/autoload.php

### ISSUE THREAD

**Issue by Xoferek** [nicelife90/BladeBTC#12]
Hi

From where i can download this file ?

**Comment by Xoferek** [comment]
And same new problem. 
PHP Fatal error:  Call to a member function getText() on null in /var/www/bot/BladeBTC/WebHookHandler.php on line 50

**Comment by nicelife90** [comment]
Check the install instruction and go to realese tab to dowload the installer.

The autoload file was generated by composer.

Le 19 sept. 2018 14 h 54, Xoferek <notifications@github.com> a écrit :

Hi

From where i can download this file ?

**Comment by Xoferek** [comment]
I made all via installer.sh and i have this fatal error.

**Comment by muc1** [comment]
same here. any solutions?

**Comment by nicelife90** [comment]
I'm thinking about creating a new version fully compatible with latest version of the technology!
Subscribe to get the latest information.
