### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by JohnSCS** [nicelife90/BladeBTC#13]
Does this install work on Amazon EC2 servers?
I have installed and no response from bot, or web browser.

**Comment by nicelife90** [comment]
You need to manage your firewall on aws and the webpage will be blank its normal

Le 21 sept. 2018 11 h 32, JohnSCS <notifications@github.com> a écrit :

Does this install work on Amazon EC2 servers?
I have installed and no response from bot, or web browser.

**Comment by JohnSCS** [comment]
I have opened all ports on the server. 
You hit start on the bot, and it says ‘Typing’ then nothing.

**Comment by nicelife90** [comment]
Than check the telegram api documentation they have an url gived to check if your webhook is set correctly you can also enable debug mode in the .env file to seed any error by going to your website in a browser.

Le 21 sept. 2018 11 h 32, JohnSCS <notifications@github.com> a écrit :

Does this install work on Amazon EC2 servers?
I have installed and no response from bot, or web browser.

**Comment by nicelife90** [comment]
No working with last version of ubuntu because of PHP version

Le 21 sept. 2018 11 h 32, JohnSCS <notifications@github.com> a écrit :

Does this install work on Amazon EC2 servers?
I have installed and no response from bot, or web browser.

**Comment by JohnSCS** [comment]
Using Ubuntu 14.04 LTS

**Comment by JohnSCS** [comment]
All working now. Cheers
