### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by coderwashere** [nicelife90/BladeBTC#16]
HTTP ERROR 500
this error shown in the host link that i used (domain or the ip of host)
bot looks like work good but it cant invest on it ->>
""An error occurred while generating your payment address.
Please contact support with this account ID ""

so i think this not working because error 500 in website.
my php 7.0 i try use 5.6 and same problem + bot stop working.
when i back to 7.0 bot work again but problem of invest still there!
i also try to remove .htaccess and same problem
help me please !

**Comment by muc1** [comment]
How do you access the bot to see that he is working?

**Comment by coderwashere** [comment]
from telegram app

**Comment by coderwashere** [comment]
muc1 give me your facebook or any contact way i will help you.

also when i press on Withdraw it says.
"Your withdraw address is not set
Please set your correct withdraw address first"
i but my wallet id in chat but it still say i didnt set my id !!

**Comment by muc1** [comment]
@AlexMuc1 on telegram

**Comment by coderwashere** [comment]
any help !

**Comment by nicelife90** [comment]
OK first thing first this application is not compatible with PHP 7
My first thinking is about the linux version version that are you using.
Blockchain Wallet service is compatible with certain nodejs version and i think this is your error.

Try using the right linux version recommended by my instruction https://github.com/nicelife90/BladeBTC

I'm very busy but I have a lot of request about this little script maybe i will make an updated version of this script compatible with the latest version of the technology when i have some times to spent.

**Comment by enea1982** [comment]
hello I wrote you in the mail you could answer thanks ?
