### ISSUE TITLE
Invest Error

### ISSUE THREAD

**Issue by GrinFlame** [nicelife90/BladeBTC#17]
Hi nicelife90, I'm getting an error when I click invest in the bot chat can you please help? Seems to be like its not logging in or do you need have BTC in the blockchain account first.

"An error occurred while generating your payment address.
Please contact support with this account ID : 653496879. 😖"

Thanks

**Comment by nicelife90** [comment]
Hi,

this error is related to the blockchain wallet or node.js.
Almost of the time this error is throw when the blockchain wallet is not corectlyr configure.

Maybe you have two not withelisted your server IP in your blockchain wallet or you use two factor auuth and youd dont provide your two password.
