### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by keezie** [nicelife90/BladeBTC#20]
Hi,

Is there an admin panel?
if yes how to acces it?

regards,

**Comment by netfr13nd** [comment]
no admin panel

**Comment by nicelife90** [comment]
Hi,

They have no admin panel at this time.

Thank you!

Le 18 déc. 2018 08 h 45, keezie <notifications@github.com> a écrit :

Hi,

Is there an admin panel?
if yes how to acces it?

regards,

**Comment by Donstesh** [comment]
I don't see the settings for setting up IP
