### ISSUE TITLE
Bot installed but no response

### ISSUE THREAD

**Issue by synopsinvestments** [nicelife90/BladeBTC#23]
Hello sir, how are you?
I have installed bot correctly and no error appear, but I still do not get response from bot.
Server Ubuntu 14.04

What can be wrong ? is there any command to run bot or it will automatically run?
Also what configuration needed to make BotFather ? ( Customize and put your new bot inline with BotFather )

Thanks

**Comment by nicelife90** [comment]
I found a bug that is impacting this script in some particular and specific case. I will correct the script soon with a new version for Ubuntu18.04LTS and I will release a paid version with web base control panel.

**Comment by nicelife90** [comment]
The bot should be always responding now many bug fix was made.

**Comment by xscuvalar** [comment]
Bot not responding and I've done everything correctly.
