### ISSUE TITLE
Where I need to save the Application ID from the BotFather

### ISSUE THREAD

**Issue by enea1982** [nicelife90/BladeBTC#25]
in the instructions is missing where to put the botfather codes and how to start the bot??

**Comment by nicelife90** [comment]
The BotFather API Code need to be put in the install script. If you follow the install insctruction you will see where to put this information while you do the procedure. Futher more this information will be writed in the file /var/www/bot/.env that is the main configuration file of the Bot.

**Comment by nicelife90** [comment]
The BotFather API key is now saved in the database. The .env file is now only for debug and for database credentials.
