### ISSUE TITLE
Balance not updating after active investment

### ISSUE THREAD

**Issue by rand9607** [nicelife90/BladeBTC#26]
When I Invest and it becomes an active investement, the bot places the right amount of profit into the balance but as soon as the active investment is expired it doesn't credit your btc back to /balance.   So you're left with a balance that just consists of your profit

**Comment by nicelife90** [comment]
This situation will need to be tested. I will check this and correct the situation in the next release if this situation is present.

**Comment by nicelife90** [comment]
At the moment that I was writed this little script. The balance was alwas kepp by the system at the end of the investment. Now after a contract end the balance will be updated.
