### ISSUE TITLE
Install script ouput warning - Installer run more than once

### ISSUE THREAD

**Issue by enea1982** [nicelife90/BladeBTC#27]
I install everything but stays still on

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
{"ok":true,"result":true,"description":"Webhook is already set"}
New start file created
REBOOT YOUR SERVER NOW

**Comment by nicelife90** [comment]
This output tell me that the install script was run more than one time. The install script is not supposed to be run more than once. But this message only tell that the composer dependencies is already installed and the Webhook on Telegram API website is already installed. This warning should not impact the Bot. But is you change your webhook url the bot can become not responding. I plan to improve the script in the next release.

**Comment by nicelife90** [comment]
Normaly some warning are displayed during the install like deprecated on node.js module. Also composer tell to run installation without root but these warning can be ignored.
