### ISSUE TITLE
How to start the Bot - Server Starting

### ISSUE THREAD

**Issue by enea1982** [nicelife90/BladeBTC#28]
you could help me with the Blade BTC bot

charge everything at the end remains stationary here

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
{"ok":true,"result":true,"description":"Webhook is already set"}
New start file created
REBOOT YOUR SERVER NOW
what should I do to start the bot ??

**Comment by coderwashere** [comment]
i can help you.
skype  live:samedalbrom

**Comment by enea1982** [comment]
yes thank you or installed everything but the web page remains white at the end of the installation it tells me to restart the server I restart the raspberry but the bot does not start

**Comment by Donstesh** [comment]
I also need help to install the bot

**Comment by nicelife90** [comment]
I found a bug that is impacting this script in some particular and specific case. I will correct the script soon with a new version for Ubuntu18.04LTS and I will release a paid version with web base control panel.

The bot is starting by itself upon server start while the Bot is mainly a web application hosted i'm apache2.

**Comment by nicelife90** [comment]
All the service should go up at each restart.
