### ISSUE TITLE
REBOOT SERVER NOW - Not Rebooting

### ISSUE THREAD

**Issue by enea1982** [nicelife90/BladeBTC#29]
hello you can help me start the bot?

when it says restart the server restart the raspberry pi but it does not work like never ?

**Comment by nicelife90** [comment]
When the script tell REBOOT SERVER NOW it was an instruction not and indication that the server will be restarted. Maybe this output is not good enough to help user to complete the installation process. I will correct this in the next release.

**Comment by nicelife90** [comment]
The server will now reboot and put all service up at the starting time.
