### ISSUE TITLE
About Blockchain

### ISSUE THREAD

**Issue by rheyjohn10** [nicelife90/BladeBTC#3]
sir how I can fix this sir.. im using free vps ,ubuntu 14.04  i dont have any money sir..can u help me with this problem sir.. pls.. thnk you in advance

![sketch 4](https://user-images.githubusercontent.com/40140270/41572509-cb12eaca-73aa-11e8-9cb3-0564117a0cd8.png)

**Comment by nicelife90** [comment]
Be sure that the VM was rebooted after the script as done the installation process. Be sure to withe list your VM IP in your Blockchain wallet. Be sure that the wallet service run in your VM using top or htop command.

**Comment by rheyjohn10** [comment]
yes sir i reboot after the installation, and the ip is already set to whitelist sir ..this is the error log sir ..I dont know how to fix 
/workspace$ sudo tail /var/log/apache2/error.log
[Tue Jun 19 00:12:35.683831 2018] [core:notice] [pid 592] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 19 00:14:28.334832 2018] [authz_core:error] [pid 1340] [client 127.0.0.1:49525] AH01630: client denied by server configuration: /var/www/merchant
[Tue Jun 19 00:15:44.509352 2018] [authz_core:error] [pid 1340] [client 127.0.0.1:51154] AH01630: client denied by server configuration: /var/www/merchant
[Tue Jun 19 00:16:13.137215 2018] [authz_core:error] [pid 645] [client 127.0.0.1:51713] AH01630: client denied by server configuration: /var/www/merchant
[Tue Jun 19 00:17:17.430798 2018] [authz_core:error] [pid 1340] [client 127.0.0.1:53099] AH01630: client denied by server configuration: /var/www/merchant
[Tue Jun 19 00:22:16.427322 2018] [authz_core:error] [pid 642] [client 127.0.0.1:59060] AH01630: client denied by server configuration: /var/www/merchant
[Tue Jun 19 02:02:51.535571 2018] [mpm_prefork:notice] [pid 592] AH00169: caught SIGTERM, shutting down
[Tue Jun 19 04:00:43.251235 2018] [mpm_prefork:notice] [pid 523] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.25 OpenSSL/1.0.1f configured -- resuming normal operations
[Tue Jun 19 04:00:43.251333 2018] [core:notice] [pid 523] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 19 04:03:34.327570 2018] [authz_core:error] [pid 530] [client 127.0.0.1:51554] AH01630: client denied by server configuration: /var/www/merchant

**Comment by afoke** [comment]
I am having the same issue as well. Bot is unable to generate payment address.

**Comment by nicelife90** [comment]
@rheyjohn10 Generally speaking this is an issue  with your apache2 configuration. Normally the install script create a vhost with your domain name in /etc/apache2/site-availlables/ with something like this :

```
<VirtualHost *:80>
			
				#general
				ServerAdmin webmaster@$DOMAIN
				ServerName $DOMAIN
				ServerAlias $DOMAIN
				
				#directory
				DocumentRoot /var/www/bot/
				<Directory />
					AllowOverride All
				</Directory>
				**<Directory /var/www/bot/>
					Options -Indexes +FollowSymLinks +MultiViews
					AllowOverride all
					Require all granted
				</Directory>**
				
				#log
				ErrorLog /var/log/apache2/$DOMAIN-error.log
				LogLevel error
				CustomLog /var/log/apache2/$DOMAIN-access.log combined
				
			</VirtualHost>
```

The bold part is important in that case.

**Comment by nicelife90** [comment]
To keep it simple to install :

1. Download the release [From this link](https://github.com/nicelife90/BladeBTC/releases/download/1.1.0/install.zip)

and 

On a fresh install of Ubuntu 14.04.5 LTS do the following commands :

    Upload install.zip to /var/tmp

    Use apache2 when the installer.sh ask you for a choice!

$ cd /var/tmp
$ sudo apt-get install -y unzip dos2unix
$ unzip install.zip
$ cd install/
$ dos2unix installer.sh
$ chmod 777 installer.sh
$ sudo ./installer.sh

    Follow the script instruction and give all the required data.
    Reboot your server.

**Comment by afoke** [comment]
The issue is below. I think the script is failing to authenticate when you tap on the invest button. Can you look into this?

<img width="893" alt="terminal" src="https://user-images.githubusercontent.com/16977112/41727932-9220012c-7543-11e8-8be1-2b6fb0374bb6.png">

**Comment by coderwashere** [comment]
this didnt work for me
