### ISSUE TITLE
Do you provide any support - Installation service

### ISSUE THREAD

**Issue by enea1982** [nicelife90/BladeBTC#30]
hello you can help me to install the BladeBtc bot

**Comment by nicelife90** [comment]
By the time that started to share this project each day many users reach me to get help to install to script. The script by itself is very simple. But, all the dependencies required by this application can be complex to understand for simple user. In other word to fully understand all the life cycle of this application you will need skills in all the following technologies : PHP, node.js, API, Blockchain, Bitcoin, Blockchain Wallet API, Blockchain Wallet Service, Telegram API, Linux Service, LAMP. This is the minimum requirement to modify this script by yourself.

So... while I have to many request to support the install process, Starting from today, I offer an install service on your private server for 150$ US. I will accept payment in bitcoin and I will wait a minimum of 3 validation before processing your installation. I will also accept PayPal payment.

You can contact me at ylafontaine@alarmeatc.com and put INSTALLATION SERVICE as subject to order this services.

Thank you

**Comment by mmogodvn** [comment]
I can help you install it.

**Comment by nicelife90** [comment]
> I can help you install it.

Yes I can!

**Comment by enea1982** [comment]
can you help me to install it today

Il giorno gio 23 mag 2019 alle 18:25 Yanick Lafontaine <
notifications@github.com> ha scritto:
