### ISSUE TITLE
What Linux distribution I need - What PHP version I need

### ISSUE THREAD

**Issue by enea1982** [nicelife90/BladeBTC#32]
i think its the php version
should i downrage to the 5.6?

_Originally posted by @muc1 in https://github.com/nicelife90/BladeBTC/issues/14#issuecomment-426349149_

yes thank you or installed everything but the web page remains white at the end of the installation it tells me to restart the server I restart the raspberry but the bot does not start

**Comment by nicelife90** [comment]
This script is currently working with Ubuntu 14.04 LTS only.
All PHP 5.x version should work for this application. PHP 7.x will never work without modification of the application.

**Comment by enea1982** [comment]
> 
> 
> This script is currently working with Ubuntu 14.04 LTS only.
> All PHP 5.x version should work for this application. PHP 7.x will never work without modification of the application.
> 
> I plan to release new version compatible with the last LTS version of Ubuntu and PHP 7.x.

hi I paid you but you still haven't answered me you can do the job of the bot ?

**Comment by enea1982** [comment]
> 
> 
> This script is currently working with Ubuntu 14.04 LTS only.
> All PHP 5.x version should work for this application. PHP 7.x will never work without modification of the application.
> 
> I plan to release new version compatible with the last LTS version of Ubuntu and PHP 7.x.

hello you can answer my e-mail please?

**Comment by nicelife90** [comment]
For now using the latest Ubuntu 18.04LTS will work. PHP7 is now supported.
