### ISSUE TITLE
Error occurred while generating your payment address.

### ISSUE THREAD

**Issue by AK064** [nicelife90/BladeBTC#37]
I have tried to white list the ip in blockchain wallet and checked node.js.

**Comment by Donstesh** [comment]
whats your error? kindly share a screen shot

**Comment by Donstesh** [comment]
Make sure you have listed your server IP to the blockchain whitelist

**Comment by nicelife90** [comment]
You need to whitelist your server IP address in your blockchain wallet.

De : Stephen Shifoko <notifications@github.com>
Envoyé : 5 avril 2019 14:38
À : nicelife90/BladeBTC <BladeBTC@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [nicelife90/BladeBTC] Error occurred while generating your payment address. (#37)


Make sure you have listed your server IP to the blockchain whitelist
