### ISSUE TITLE
Err_Auth

### ISSUE THREAD

**Issue by afoke** [nicelife90/BladeBTC#4]
The issue is below. I think the script is failing to authenticate when you tap on the invest button. Can you look into this?

<img width="893" alt="41727932-9220012c-7543-11e8-8be1-2b6fb0374bb6" src="https://user-images.githubusercontent.com/16977112/41734187-373990dc-7554-11e8-9875-21142516f829.png">

**Comment by afoke** [comment]
Still doesn't work.

**Comment by nicelife90** [comment]
Normally you receive an email that indicate that a request have been made and you need to accept. Also in parameters > security > advance settings you need to disable two step authentication and put your vm in witelist.
