### ISSUE TITLE
ERROR 1064 (42000) at line 21: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by zzzzre** [nicelife90/BladeBTC#48]
Hi, At the end of today's patch gives the following:
Creating Database ... [PLEASE WAIT]
./install.sh: line 381: investment: command not found
./install.sh: line 381: investment: command not found
./install.sh: line 381: telegram_id: command not found
./install.sh: line 381: amount: command not found
./install.sh: line 381: rate: command not found
./install.sh: line 381: contract_end_date: command not found
./install.sh: line 381: contract_start_date: command not found
./install.sh: line 381: referrals: command not found
./install.sh: line 381: referrals: command not found
./install.sh: line 381: telegram_id_referent: command not found
./install.sh: line 381: telegram_id_referred: command not found
./install.sh: line 381: bind_date: command not found
./install.sh: line 381: transactions: command not found
./install.sh: line 381: transactions: command not found
./install.sh: line 381: telegram_id: command not found
./install.sh: line 381: amount: command not found
./install.sh: line 381: withdraw_address: command not found
./install.sh: line 381: message: command not found
./install.sh: line 381: tx_hash: command not found
./install.sh: line 381: notice: command not found
./install.sh: line 381: status: command not found
./install.sh: line 381: telegram_username: command not found
./install.sh: line 381: telegram_first: command not found
./install.sh: line 381: telegram_last: command not found
./install.sh: line 381: telegram_id: command not found
./install.sh: line 381: balance: command not found
./install.sh: line 381: invested: command not found
./install.sh: line 381: profit: command not found
./install.sh: line 381: commission: command not found
./install.sh: line 381: payout: command not found
./install.sh: line 381: rate: command not found
./install.sh: line 381: investment_address: command not found
./install.sh: line 381: last_confirmed: command not found
./install.sh: line 381: wallet_address: command not found
./install.sh: line 381: referral_link: command not found
./install.sh: line 381: created_at: command not found
./install.sh: line 381: investment: command not found
./install.sh: line 381: investment: command not found
./install.sh: line 381: referrals: command not found
./install.sh: line 381: referrals: command not found
./install.sh: line 381: telegram_id_referred: command not found
./install.sh: line 381: telegram_id_referred: command not found
./install.sh: line 381: transactions: command not found
./install.sh: line 381: transactions: command not found
./install.sh: line 381: telegram_id: command not found
./install.sh: line 381: telegram_id: command not found
./install.sh: line 381: investment: command not found
./install.sh: line 381: investment: command not found
./install.sh: line 381: referrals: command not found
./install.sh: line 381: referrals: command not found
./install.sh: line 381: transactions: command not found
./install.sh: line 381: transactions: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: first_name: command not found
./install.sh: line 381: last_name: command not found
./install.sh: line 381: username: command not found
./install.sh: line 381: password: command not found
./install.sh: line 381: email: command not found
./install.sh: line 381: profile_img: command not found
./install.sh: line 381: last_login_date: command not found
./install.sh: line 381: last_login_ip: command not found
./install.sh: line 381: login_attempt: command not found
./install.sh: line 381: account_group: command not found
./install.sh: line 381: inscription_date: command not found
./install.sh: line 381: deleted: command not found
./install.sh: line 381: deleted_date: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: first_name: command not found
./install.sh: line 381: last_name: command not found
./install.sh: line 381: username: command not found
./install.sh: line 381: password: command not found
./install.sh: line 381: email: command not found
./install.sh: line 381: profile_img: command not found
./install.sh: line 381: last_login_date: command not found
./install.sh: line 381: last_login_ip: command not found
./install.sh: line 381: login_attempt: command not found
./install.sh: line 381: account_group: command not found
./install.sh: line 381: inscription_date: command not found
./install.sh: line 381: deleted: command not found
./install.sh: line 381: deleted_date: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: group_name: command not found
./install.sh: line 381: dashboard: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: group_name: command not found
./install.sh: line 381: dashboard: command not found
./install.sh: line 381: gui_mail_group: command not found
./install.sh: line 381: gui_mail_group: command not found
./install.sh: line 381: group_name: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: mail_group_id: command not found
./install.sh: line 381: email: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: menu_id: command not found
./install.sh: line 381: title: command not found
./install.sh: line 381: icon: command not found
./install.sh: line 381: display_order: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: menu_id: command not found
./install.sh: line 381: title: command not found
./install.sh: line 381: icon: command not found
./install.sh: line 381: display_order: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: description: command not found
./install.sh: line 381: name: command not found
./install.sh: line 381: icon: command not found
./install.sh: line 381: access_level: command not found
./install.sh: line 381: parent: command not found
./install.sh: line 381: static: command not found
./install.sh: line 381: visits: command not found
./install.sh: line 381: last_visit: command not found
./install.sh: line 381: active: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: description: command not found
./install.sh: line 381: name: command not found
./install.sh: line 381: icon: command not found
./install.sh: line 381: access_level: command not found
./install.sh: line 381: parent: command not found
./install.sh: line 381: static: command not found
./install.sh: line 381: visits: command not found
./install.sh: line 381: last_visit: command not found
./install.sh: line 381: active: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: rbac_items_id: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: rbac_items_id: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: description: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: description: command not found
./install.sh: line 381: gui_setting: command not found
./install.sh: line 381: gui_setting: command not found
./install.sh: line 381: setting_name: command not found
./install.sh: line 381: setting_value: command not found
./install.sh: line 381: description: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: username: command not found
./install.sh: line 381: username: command not found
./install.sh: line 381: account_group: command not found
./install.sh: line 381: account_group: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: gui_mail_group: command not found
./install.sh: line 381: gui_mail_group: command not found
./install.sh: line 381: group_name: command not found
./install.sh: line 381: group_name: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: mail_group_id: command not found
./install.sh: line 381: mail_group_id: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: menu_id: command not found
./install.sh: line 381: menu_id: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: rbac_items_id: command not found
./install.sh: line 381: rbac_items_id: command not found
./install.sh: line 381: rbac_items_id: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: gui_setting: command not found
./install.sh: line 381: gui_setting: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: gui_account: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: gui_mail_group: command not found
./install.sh: line 381: gui_mail_group: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: gui_menu: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: gui_module: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: gui_setting: command not found
./install.sh: line 381: gui_setting: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: gui_mail_group_member: command not found
./install.sh: line 381: gui_mail_group_member_ibfk_1: command not found
./install.sh: line 381: mail_group_id: command not found
./install.sh: line 381: gui_mail_group: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: gui_rbac_assignment: command not found
./install.sh: line 381: gui_rbac_assignment_ibfk_1: command not found
./install.sh: line 381: rbac_items_id: command not found
./install.sh: line 381: gui_rbac_items: command not found
./install.sh: line 381: gui_rbac_assignment_ibfk_2: command not found
./install.sh: line 381: group_id: command not found
./install.sh: line 381: gui_group: command not found
./install.sh: line 381: group_id: command not found
ERROR 1064 (42000) at line 21: You have an error in your SQL syntax; check the m                                                                                        anual that corresponds to your MariaDB server version for the right syntax to us                                                                                        e near '(
                              uid=0(root) gid=0(root) groups=0(root)          '                                                                                         at line 1

This is the only error during installation.

**Comment by nicelife90** [comment]
Hi this error come from the branch 18.04 LTS. The install is not ready!
