### ISSUE TITLE
ETH

### ISSUE THREAD

**Issue by mdiersma** [nicelife90/BladeBTC#5]
**Describe the solution you'd like**
Would be nice to add ETH support for blockchain.com

**Comment by nicelife90** [comment]
Hello,

At the time of writing this script Ethereum did not exist. I will keep your proposal in mind and add support for this currency if I modify the script.

**Comment by nicelife90** [comment]
> **Describe the solution you'd like**
> Would be nice to add ETH support for blockchain.com

The blockchain wallet service is not supporting ETH at this time. I will not add this to the bot for now.
