### ISSUE TITLE
russian translation

### ISSUE THREAD

**Issue by glebkhil** [nicelife90/BladeBTC#50]
Can not translate into Russian. I am changing words in the WebHookHandler.php file and in files from the Commands folder. What am I doing wrong?

**Comment by nicelife90** [comment]
You need to change the text from each keyboard in all command file.

	$keyboard = [
				["My balance " . Btc::Format($user->getBalance()) . " \xF0\x9F\x92\xB0"],
				["Invest \xF0\x9F\x92\xB5", "Withdraw \xE2\x8C\x9B"],
				["Reinvest \xE2\x86\xA9", "Help \xE2\x9D\x93"],
				["My Team \xF0\x9F\x91\xAB"],
			];
