### ISSUE TITLE
Deposit

### ISSUE THREAD

**Issue by zzzzre** [nicelife90/BladeBTC#52]
HI,I  installed the bot, the bot works, I click "Invest 💵" the bot gives the address, I send bitcoins to it, a lot of confirmations go through, but this amount does not appear anywhere in the bot as if it didn't send anything

**Comment by zzzzre** [comment]
When this command "gwb" works correctly and shows the amount on the purse

**Comment by mmogodvn** [comment]
Cron job not work. Kkk. Plaza check in cronjob setting

**Comment by zzzzre** [comment]
Cron what's this? I do not quite understand

**Comment by nicelife90** [comment]
Wich branch are you using if is the master branch than check if the cron job is running. Also check if you have any error running cron_deposit.php.


Le 16 mai 2019 02 h 58, smile <notifications@github.com> a écrit :

HI,I installed the bot, the bot works, I click "Invest 💵" the bot gives the address, I send bitcoins to it, a lot of confirmations go through, but this amount does not appear anywhere in the bot as if it didn't send anything

**Comment by enea1982** [comment]
hello between how much the update ends?

**Comment by nicelife90** [comment]
1 or 2 weeks

Le 21 mai 2019 16 h 07, enea1982 <notifications@github.com> a écrit :

hello between how much the update ends?

**Comment by enea1982** [comment]
but 1 or 2 weeks was 2 weeks ago

Il giorno mar 21 mag 2019 alle 23:56 Yanick Lafontaine <
notifications@github.com> ha scritto:

> 1 or 2 weeks
>

**Comment by nicelife90** [comment]
All issue with deposit was now fix in the latest version!
