### ISSUE TITLE
Telegram bot not work

### ISSUE THREAD

**Issue by mmogodvn** [nicelife90/BladeBTC#54]
I'm install done. Gui work well. I can login to dashboard. But when using telegram to start bot, it not work. No response from bot. I think there is a bug in the webhook functions. Please help me fix it.
Thank you so much.

**Comment by nicelife90** [comment]
There is no bug with Webhook. Please paste send me your apache error log.

Le 23 mai 2019 20 h 01, mmogodvn <notifications@github.com> a écrit :

I'm install done. Gui work well. I can login to dashboard. But when using telegram to start bot, it not work. No response from bot. I think there is a bug in the webhook functions. Please help me fix it.
Thank you so much.

**Comment by zzzzre** [comment]
So wasn't a bot, but after sudo apt-get install curl bot has earned.
Now the problem comes BladeBTC GUI - invalid login or password

**Comment by zzzzre** [comment]
how to login to BladeBTC GUI ?

**Comment by zzzzre** [comment]
Noticed another problem: 
1 - does not consider referrals (always 0 referrals)
2 - after you start the bot after a while POPs up sooobschenie: Your deposit of <b>0.001</b> is now accepted and invested. You will recover this amount with interest in your balance at the end of your contract.
and in the column "Active ivestment" appears in the amount of 0.001 BTC

**Comment by nicelife90** [comment]
> how to login to BladeBTC GUI ?

OK so I was thinking the default username and password was in the readme.
I updated the readme with the correct information.

The default username and password is: bladebtc

**Comment by nicelife90** [comment]
> So wasn't a bot, but after sudo apt-get install curl bot has earned.
> Now the problem comes BladeBTC GUI - This username is invalid.

I will update the install script to be sure that curl is installed.

**Comment by nicelife90** [comment]
Ok so I'll close this issue I fixed the install script and opened 2 new issue about refferals and deposit.

**Comment by enea1982** [comment]
> > So wasn't a bot, but after sudo apt-get install curl bot has earned.
> > Now the problem comes BladeBTC GUI - This username is invalid.
> 
> I will update the install script to be sure that curl is installed.

referrals don't work??

**Comment by enea1982** [comment]
or installed the script perfectly and the withdraw from error again
