### ISSUE TITLE
referrals not working

### ISSUE THREAD

**Issue by nicelife90** [nicelife90/BladeBTC#55]
Noticed another problem: 
1 - does not consider referrals (always 0 referrals)

_Originally posted by @zzzzre in https://github.com/nicelife90/BladeBTC/issues/54#issuecomment-495573942_

**Comment by enea1982** [comment]
hello i can get some help you can answer me on the mail

**Comment by enea1982** [comment]
or installed the script perfectly and the withdraw from error again

**Comment by enea1982** [comment]
referral problem

**Comment by nicelife90** [comment]
The refferal system was working again.

**Comment by zzzzre** [comment]
An error occurred.
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`telegram_bot`.`referrals`, CONSTRAINT `referrals_ibfk_2` FOREIGN KEY (`telegram_id_referred`) REFERENCES `users` (`telegram_id`) ON DELETE CASCADE ON UPDATE CASCADE). 

**Comment by enea1982** [comment]
> The refferal system was working again.

hello the referal system from problems??
