### ISSUE TITLE
Cron Deposit - Add balance on empty address

### ISSUE THREAD

**Issue by nicelife90** [nicelife90/BladeBTC#56]
Noticed another problem: 

2 - after you start the bot after a while POPs up message: Your deposit of <b>0.001</b> is now accepted and invested. You will recover this amount with interest in your balance at the end of your contract.
and in the column "Active ivestment" appears in the amount of 0.001 BTC

_Originally posted by @zzzzre in https://github.com/nicelife90/BladeBTC/issues/54#issuecomment-495573942_

**Comment by zzzzre** [comment]
Checked referrals are also not showing, and a Deposit of 0.001 is created itself 3 minutes after the start of the bot



My Stats

Total referrals : 0

Members | Active | Invest
0 | 0 | 0.00000000 BTC

Your deposit of <b>0.001</b> is now accepted and invested. You will recover this amount with interest in your balance at the end of your contract.

My balance 0.00000000 💰

Your account balance:
0.00000000 BTC

Total invested:
0.00100000 BTC

Active investment:
0.00100000 BTC

Total profit:
0.00000000 BTC

Total Payout:
0.00000000 BTC

Total commission:
0.00000000 BTC

Your investment:

|   Amount   |   Rate   |   End   |
|0.00100000|6%|2019-06-23 18:05:02|


Base rate: 6% per day for 30 days

You may start another investment by pressing the "Invest" button. Your balance will grow according to the base rate.

this Deposit is created independently after 3 minutes after starting the bot

**Comment by nicelife90** [comment]
Yes i see the bug with the deposit.

**Comment by nicelife90** [comment]
OK! So the problem is: By now the deposit check each wallet address, while doing this the script check if the wallet address have a label and if this label is not empty the script try to build an object of type USER. If object can be build that meen that a user is found in database. So after he will check if the amount confirmed on this adress is the same in the database. If not he will add the investment into the database and create an investment.

That meen if you delete a user and he return to your bot generating new adress he will get is old deposit.

I will need to add condition on that but i will need to think about the impact.

**Comment by nicelife90** [comment]
this is now fixed
