### ISSUE TITLE
Bot not work, GUI is very well

### ISSUE THREAD

**Issue by mmogodvn** [nicelife90/BladeBTC#57]
I try on new Ubuntu server but my bot not work. 
i can't start it. 
I can log in to GUI, everything are well.
Please check it.
p/s: Attach file is apache log file
[meomeo.shop-access.log](https://github.com/nicelife90/BladeBTC/files/3221525/meomeo.shop-access.log)

**Comment by mmogodvn** [comment]
It work now, after 30 min install. LOL

**Comment by partrotic** [comment]
Installation worked after following the READ ME installation guide but bot not working who can help
