### ISSUE TITLE
Referral error

### ISSUE THREAD

**Issue by zzzzre** [nicelife90/BladeBTC#58]
Updated bot:
using sudo-s
cd /var/tmp/BladeBTC
./install.sh
When the referral comes error: An error occurred.
SQLSTATE23000: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (telegrambot.referrals, referralsibfk2 CONSTRAINT FOREIGN KEY (telegramidreferred) REFERENCES users (telegramid) ON DELETE CASCADE ON UPDATE CASCADE). ,
Reset the bot, the error persists

**Comment by nicelife90** [comment]
did you install the script before I made the updater.
If yes you need to reinstall.

so drop or rename the database telegram_bot using command line or phpmyadmin.
Than run this

sudo -s
cd /var/tmp
rm -rf BladeBTC
git clone https://github.com/nicelife90/BladeBTC.git
cd BladeBTC/
chmod 550 install.sh
./install.sh

cheers

**Comment by nicelife90** [comment]
after that you can do the update using the procedure in the readme.

**Comment by zzzzre** [comment]
I checked again, created a new bot and installed everything on a new one, the one who clicks on the referral link gets an error: An error occurred.
SQLSTATE23000: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (telegrambot.referrals, referralsibfk2 CONSTRAINT FOREIGN KEY (telegramidreferred) REFERENCES users (telegramid) ON DELETE CASCADE ON UPDATE CASCADE).

**Comment by zzzzre** [comment]
Make a check on the newly created bot

**Comment by nicelife90** [comment]
give me your server information

Le 27 mai 2019 23 h 22, smile <notifications@github.com> a écrit :

I checked again, created a new bot and installed everything on a new one, the one who clicks on the referral link gets an error: An error occurred.
SQLSTATE23000: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (telegrambot.referrals, referralsibfk2 CONSTRAINT FOREIGN KEY (telegramidreferred) REFERENCES users (telegramid) ON DELETE CASCADE ON UPDATE CASCADE).

**Comment by zzzzre** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Comment by nicelife90** [comment]
no like your access i will check
________________________________
De : smile <notifications@github.com>
Envoyé : 28 mai 2019 14:50
À : nicelife90/BladeBTC
Cc : Yanick Lafontaine; Comment
Objet : Re: [nicelife90/BladeBTC] Referral error (#58)


Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**Comment by zzzzre** [comment]
If you go to the bot not using a referral link , and then it is to Ref all works as it should, and if for the first time on the referral error

**Comment by zzzzre** [comment]
Dear developer, I have not found a solution to the problem with the referral system

**Comment by zzzzre** [comment]
Please tell me how to make a referral recharge notification; I’m doing this doesn’t work: 
 /**
     /**
                             * Send user message - Notification of commission
                             */
                            $apiToken = BotSetting::getValueByName('app_id');
                            $data = [
                                'parse_mode' => 'HTML',
                                'chat_id' => $user->getTelegramId(),
                                'text' => 'New Referral Invesment <b>' . BTC::Format($commission) . .'
                            ];
                            $response = file_get_contents("https://api.telegram.org/bot$apiToken/sendMessage?" . http_build_query($data));
                        }
    }
}

**Comment by paydead1** [comment]
hello nicelife90. i'm unable to login to my phpmyadmin please i need help on that 
i installed  the script without error

**Comment by nicelife90** [comment]
> TIMER_TIME_HOUR



> 
> 
> Dear developer, Can you please tell why with any parameter "TIMER_TIME_HOUR" the bot still counts and credits the balance every 4 hours


Hi,

the TIMER_TIME_HOUR value should never be edited. This value is used as a constant to calculate interest. I you modify this value the interest will be calculated incorectly. Also editing this value will not impact the interest frequency. To edit the interest frequency youd need to look at your cron job.

**Comment by nicelife90** [comment]
> 
> 
> hello nicelife90. i'm unable to login to my phpmyadmin please i need help on that
> i installed the script without error

Try to login with root as user and your server password. Or try your server user and server password.

**Comment by nicelife90** [comment]
> 'text' => 'New Referral Invesment ' . BTC::Format($commission) . .'

This line should be like this:

'text' => 'New Referral Invesment ' . BTC::Format($commission) 

remove ..'

**Comment by nicelife90** [comment]
Fixed referal system
