### ISSUE TITLE
No Response from BOT

### ISSUE THREAD

**Issue by partrotic** [nicelife90/BladeBTC#60]
Thank you nicelife90 for the job...i tried configuring the bladeBTC for educational purpose those no problem occurred during installation. but the thing now is my telegram bot is not bringing out options for user to communicate with the bot, secondly user is not appearing on the GUI dashboard. try to look at it

**Comment by partrotic** [comment]
I followed all the READ ME installation guide. I will appreciate it if you can drop the telegram bot that is working.

**Comment by paydead1** [comment]
Thank you nicelife90 for the job...i tried configuring the bladeBTC for educational purpose those no problem occurred during installation
i can't login to my phpmyadmin

**Comment by nicelife90** [comment]
Everything should work now!
