### ISSUE TITLE
translate

### ISSUE THREAD

**Issue by deataxe** [nicelife90/BladeBTC#7]
does not see Russian
how to fix???
elseif (preg_match("/\bBalance\b/i", $text))
elseif (preg_match("/\bБаланс\b/i", $text)) 

			$keyboard = [
				["Баланс " . Btc::Format($user->getBalance()) . " \xF0\x9F\x92\xB0"],
				["Invest \xF0\x9F\x92\xB5", "Withdraw \xE2\x8C\x9B"],
				["Reinvest \xE2\x86\xA9", "Help \xE2\x9D\x93"],
				["My Team \xF0\x9F\x91\xAB"],

**Comment by deataxe** [comment]
utf -8 без bom

**Comment by glebkhil** [comment]
it turned out to translate into Russian?
