### ISSUE TITLE
./installer.sh: line 321: /var/www/bot/localhost.sql: No such file or directory

### ISSUE THREAD

**Issue by rdpshop** [nicelife90/BladeBTC#8]
Composer could not find a composer.json file in /var/www/bot
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
./installer.sh: line 321: /var/www/bot/localhost.sql: No such file or directory
{"ok":false,"error_code":404,"description":"Not Found"}
New start file created

**Comment by nicelife90** [comment]
Hi,

I think this is the result of cloning the repo. You need to use the install release. 

[Install](https://github.com/nicelife90/BladeBTC/releases/download/1.1.0/install.zip)

Put this zip file in /var/tmp and do the following commands :

$ cd /var/tmp
$ sudo apt-get install -y unzip dos2unix
$ unzip install.zip
$ cd install/
$ dos2unix installer.sh
$ chmod 777 installer.sh
$ sudo ./installer.sh

**Comment by enea1982** [comment]
> 
> 
> Composer could not find a composer.json file in /var/www/bot
> To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
> ./installer.sh: line 321: /var/www/bot/localhost.sql: No such file or directory
> {"ok":false,"error_code":404,"description":"Not Found"}
> New start file created

hello at the end when he tells me to restart the server restart the raspberry but the bot does not work
