### ISSUE TITLE
BDD?

### ISSUE THREAD

**Issue by bottest123** [nicelife90/BladeBTC#9]
What is the server BDD?what does it mean and App id does it mean Api key of bot?

**Comment by nicelife90** [comment]
Hi,

Yes app ID is the telegram API Key.
BDD is for the Database server. So the field BDD need to be filled up with your database name.

**Comment by abhisheksurela79** [comment]
hello. I'm pretty noob. I just tried to look codes. I don't know what to edit n where to edit. can u send me a completed example script. so can get some ideas what changes I need to to.

**Comment by nicelife90** [comment]
Hi,

if you follow the install instruction with the install script all the configuration file was created for you. Perhaps you need to edit the .env file at the root of your web server.

**Comment by enea1982** [comment]
hello the script starts to install it well 
in the end you give me this error you can tell me what it means?

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /var/www/bot
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
ERROR 1007 (HY000) at line 1: Can't create database 'Btcstart'; database exists
./installer.sh: riga 321: /var/www/bot/localhost.sql: File o directory non esistente
{"ok":true,"result":true,"description":"Webhook is already set"}
New start file created

**Comment by enea1982** [comment]
I want to install the bot on the raspberry pi 3 I checked and the composer.json file is there this error

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /var/www/bot
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
ERROR 1007 (HY000) at line 1: Can't create database 'Btcstart'; database exists
./installer.sh: riga 321: /var/www/bot/localhost.sql: File o directory non esistente
{"ok":true,"result":true,"description":"Webhook is already set"}
New start file created
